### ISSUE TITLE
what should I do?

### ISSUE THREAD

**Issue by fzStella** [Keenuts/vulkan-compute#2]
Hello, I want to use your Vulkan compute project to implement general computing. Can you tell me how to configure the environment？

**Comment by Keenuts** [comment]
Hello,

This is really a bare-bone compute repo to run some manual tests. It should run on linux, with Vulkan configured.
You can take a look at https://vulkan.lunarg.com/doc/view/latest/linux/getting_started.html on how to setup Vulkan on your machine.

Then running those commands should allow you to run this:
```bash
cmake -Bbuild -GNinja -H. -DSHADER_LANGUAGE=GLSL
ninja -C build
./build/sum
```

Using HLSL or WGLS shaders is also possible but requires the proper toolchain.

Good luck!

**Comment by fzStella** [comment]
Thanks, and can I setup Vulkan on the virtualbox machine ? I want to run Vulkan's general computing program on the virtual machine finally, but I can't find any method to setup Vulkan on the virtualbox. I try to setup vulkan on ubuntu system of virtualbox  according to the tutorial of configuring vulkan on linux, but failed in the end.

**Comment by Keenuts** [comment]
Not familiar with virtualbox at all. You would have to check vbox's documentation.
But from experience, if your goal is just to discover vulkan on linux, don't mix it with virtual machines. GPU & VMs are a bit of work. So I'd suggest installing linux on a computer, as main OS (look into dual boot).
If you are on Windows, Vulkan is supported (https://vulkan.lunarg.com/doc/view/latest/windows/getting_started.html), but this repo code will not work as it was written for linux.

**Comment by fzStella** [comment]
Thank you for your explanation
